"""add giftcard_url & image_url to service

Revision ID: bde3829fffc7
Revises: c955f1472619
Create Date: 2025-05-03 22:44:31.283631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde3829fffc7'
down_revision = 'c955f1472619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('unique_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.drop_constraint('gift_card_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giftcard_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint('user_transaction_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_transaction_service_id_fkey', 'service', ['service_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('amount')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('giftcard_url')

    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gift_card_service_id_fkey', 'service', ['service_id'], ['id'])
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('unique_code',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
